spring:
  application:
    name: minimal-example
    admin:
      enabled: true
      jmx-name: "${spring.jmx.default-domain}:type=admin"
  main:
    banner-mode: off
  jmx:
    enabled: false
    default-domain: ${spring.application.name}
  jackson:
    default-property-inclusion: non_null

webclient:
  default-http-connector:
    enabled: true
    timeouts:
      read:
        value: 10
      write:
        value: 10
      connect:
        value: 3

logging.level.org.zalando.logbook: TRACE

rabbit-configuration:
  connection:
    host: test_host
    port: 5672
    virtual-host: virtual_host
    username: sample_user
    password: sample_password

rabbit-messaging:
  ssl: true
  subscription-delay: 1000
  connection-name: reactor-rabbit
  queue:
    name: sample
    durable: true
    exclusive: false
    autoDelete: false
    exchange: exchange
    routing-key: routing_key
